services:
  postgres:
    image: postgres:17-alpine
    pull_policy: missing
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - postgres_rust_data:/var/lib/postgresql/data
    networks:
      - rust-network
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: rust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=user --dbname=rust"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.2-alpine
    pull_policy: missing
    ports:
      - "6379:6379"
    volumes:
      - redis_rust_data:/data
    networks:
      - rust-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Your Rust application
  app:
    build: 
      context: .
    ports:
      - "8000:8000"
    networks:
      - rust-network
    environment:
      RUST_LOG: "debug"
      RUST_BACKTRACE: "1"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - app_uploads:/app/uploads
      - ./config/docker.yaml:/config/config.yaml:ro

volumes:
  postgres_rust_data:
  redis_rust_data:
  app_uploads:

networks:
  rust-network:
    driver: bridge