services:
  postgres:
    image: postgres:17-alpine
    pull_policy: missing
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - postgres_rust_data:/var/lib/postgresql/data
    networks:
      - rust-network
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: rust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=user --dbname=rust"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.2-alpine
    pull_policy: missing
    ports:
      - "6379:6379"
    volumes:
      - redis_rust_data:/data
    networks:
      - rust-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:v1.0.1
    pull_policy: missing
    ports:
      - "1025:1025"   # SMTP server
      - "8025:8025"   # Web UI
    networks:
      - rust-network

volumes:
  postgres_rust_data:
  redis_rust_data:

networks:
  rust-network:
    driver: bridge