//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::goose_db_version::Entity as GooseDbVersion;
pub use super::mfa_backup_codes::Entity as MfaBackupCodes;
pub use super::mfa_factors::Entity as MfaFactors;
pub use super::permissions::Entity as Permissions;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::user_connections::Entity as UserConnections;
pub use super::user_credentials::Entity as UserCredentials;
pub use super::user_roles::Entity as UserRoles;
pub use super::user_verifications::Entity as UserVerifications;
pub use super::users::Entity as Users;
